version: '2'

volumes:
  nextcloud:
  dbnextcloud:

services:
  db:
    image: mariadb
    restart: always
    command: 
      - --transaction-isolation=READ-COMMITTED
      - --binlog-format=ROW
      - --innodb_read_only_compressed=OFF
    volumes:
      - dbnextcloud:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abcqwe123@
      - MYSQL_PASSWORD=abcqwe123@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  
  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=abcqwe123@
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis