version: '2'

networks: 
  common:

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    command: 
      - --transaction-isolation=READ-COMMITTED 
      - --binlog-format=ROW
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=Abcqwe123@"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Abcqwe123@
    env_file:
      - db.env
    networks:
      - common

  redis:
    container_name: redis
    image: redis:6.0.15-alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    volumes:
      - ./data/redis:/data
    networks:
      - common
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextcloud:
    container_name: nextcloud
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    expose:
      - "80"
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - VIRTUAL_HOST=nextcloud.hit.local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/cron.php"]
      interval: 5m
      timeout: 5s
      retries: 2
      #set depended on the startup time of your installation; added in v2.3
      start_period: 60s
    env_file:
      - db.env
    depends_on:
      - mariadb
      - redis
    networks:
      - common

  cron:
    container_name: cron
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    entrypoint: /cron.sh   
    depends_on:
      - mariadb
      - redis
    networks:
      - common

  nginx-proxy:
    container_name: nginx_proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro    
    networks:
      - common
